package lecho.app.campus.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PLACE_FACULTY.
 */
public class PlaceFaculty {

    private Long id;
    private Long facultyId;
    private Long placeId;

    public PlaceFaculty() {
    }

    public PlaceFaculty(Long id) {
        this.id = id;
    }

    public PlaceFaculty(Long id, Long facultyId, Long placeId) {
        this.id = id;
        this.facultyId = facultyId;
        this.placeId = placeId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFacultyId() {
        return facultyId;
    }

    public void setFacultyId(Long facultyId) {
        this.facultyId = facultyId;
    }

    public Long getPlaceId() {
        return placeId;
    }

    public void setPlaceId(Long placeId) {
        this.placeId = placeId;
    }

}
