package lecho.app.campus.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PLACE_UNIT.
 */
public class PlaceUnit {

    private Long id;
    private Long unitId;
    private Long placeId;

    public PlaceUnit() {
    }

    public PlaceUnit(Long id) {
        this.id = id;
    }

    public PlaceUnit(Long id, Long unitId, Long placeId) {
        this.id = id;
        this.unitId = unitId;
        this.placeId = placeId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUnitId() {
        return unitId;
    }

    public void setUnitId(Long unitId) {
        this.unitId = unitId;
    }

    public Long getPlaceId() {
        return placeId;
    }

    public void setPlaceId(Long placeId) {
        this.placeId = placeId;
    }

}
